### ISSUE TITLE
Unable to parse sub entries with whitespace before '#'

### ISSUE THREAD

**Issue by johangrufman** [barsoom/sie#6]
I came across a SIE-file with entries like these: 
```
#VER AT 001574 20150128
{
   #TRANS 2440 {}        -590.00 20150128 "..."
   #TRANS 2641 {}         118.00 20150128 "..."
   #TRANS 6212 {}         472.00 20150128 "..."
}
```
Notice the whitespace before the '#' on each TRANS-line. It seems like these lines are ignored by the parser because they don't match the regexp defined by `SIE::Parser::ENTRY`

It is not entirely clear to me whether the spec allows leading whitespace but it seems like at least some pieces of software writes sub entries in this style. 

As a temporary fix I monkey patched the regexp to be `ENTRY = /^\s*#/` and it solved the problem.

**Comment by tskogberg** [comment]
Yes you're right, it is a valid SIE file format. A fix for it will come shortly (tomorrow). Thank you for reporting this!

**Comment by johangrufman** [comment]
Great. Thanks!

**Comment by tskogberg** [comment]
This is fixed in https://github.com/barsoom/sie/commit/1a5ba148a1ae9aa7848fb34e99eee21296f3085c. If you use the gem, make sure to update to [3.1.1](https://rubygems.org/gems/sie/versions/3.1.1).

Thanks again for reporting this!
