### ISSUE TITLE
Thanks + you might want to mention the PHP port of your library

### ISSUE THREAD

**Issue by motin** [barsoom/sie#9]
Thanks for putting this up on Github, I recently ported your library to php: https://github.com/neam/php-sie

Might be worth mentioning in your readme as well. 

Btw, also added some tests that complemented yours: https://github.com/neam/php-sie/commit/5f9bac6a496cea015bee58e394d98f44a80743b1

**Comment by henrik** [comment]
Done. Thank you! :)
